name: oasys
description: "A new Flutter project."
publish_to: "none" # Dihapus jika Anda ingin mempublikasikannya ke pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.3
  flutter_svg: ^2.0.5
  carousel_slider: ^4.0.0
  shared_preferences: ^2.0.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_html: 3.0.0-beta.2

flutter:
  uses-material-design: true

  # Asset
  assets:
    - assets/images/headersection.png
    - assets/images/oasys-logo.png
    - assets/images/onboarding.png
    - assets/images/carousel.png
    - assets/images/noresult.png
    - assets/images/calendar.png
    - assets/images/user.png
    - assets/images/khs.png
    - assets/images/krs.png
    - assets/images/bannerinformation.png
    - assets/images/userprofile.png
    - assets/images/star.png
    - assets/images/award.png
    - assets/images/logout.png
    - assets/svg/menu.svg
    - assets/svg/discovery.svg
    - assets/svg/profile.svg
    - assets/svg/message.svg
    - assets/svg/award.svg
    - assets/svg/calendar.svg

  # Anda bisa menambahkan custom fonts di sini jika diperlukan
  fonts:
    - family: poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
